#!/usr/bin/env python3
"""Build the installable offline app (PWA) from src/calculator.html.

src/calculator.html is the page body (also published as a Claude artifact).
This writes:
  index.html            full page with app/iPad meta tags, local fonts and service worker registration
  manifest.webmanifest  app name, colours and icons
  sw.js                 service worker that caches every file so the app works offline

Run: python3 build.py
"""
import hashlib, json, pathlib, re

ROOT = pathlib.Path(__file__).resolve().parent
src = (ROOT / "src/calculator.html").read_text()

# Use the self-hosted fonts instead of Google Fonts so nothing needs the internet.
src = re.sub(r'<link rel="(?:preconnect|stylesheet)" href="https://fonts\.(?:googleapis|gstatic)\.com[^>]*>\n', "", src)

HEAD = """<!doctype html>
<html lang="en-GB">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="description" content="Ignite BA Day Calculator: what today's starter kit sales put in the retailer's pocket.">
<meta name="theme-color" content="#1d2a5e">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-title" content="BA Day">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<link rel="manifest" href="manifest.webmanifest">
<link rel="icon" type="image/png" sizes="32x32" href="icons/favicon-32.png">
<link rel="apple-touch-icon" href="icons/apple-touch-icon.png">
<link rel="stylesheet" href="fonts/fonts.css">
<style>
/* Keep content clear of the iPad status bar and home indicator when opened from the Home Screen. */
:root { padding: env(safe-area-inset-top, 0px) env(safe-area-inset-right, 0px) env(safe-area-inset-bottom, 0px) env(safe-area-inset-left, 0px); background: #1d2a5e; }
html, body { -webkit-text-size-adjust: 100%; }
button { touch-action: manipulation; }
</style>
</head>
<body>
"""

SW_REGISTER = """
<script>
if ("serviceWorker" in navigator && location.protocol !== "file:") {
  window.addEventListener("load", function () {
    var hadController = !!navigator.serviceWorker.controller;
    navigator.serviceWorker.register("sw.js").catch(function () {});
    // When a new version is installed, reload once so the BA is on the latest maths.
    navigator.serviceWorker.addEventListener("controllerchange", function () {
      if (hadController) location.reload();
    });
  });
}
</script>
</body>
</html>
"""

(ROOT / "index.html").write_text(HEAD + src + SW_REGISTER)

manifest = {
    "name": "Ignite BA Day Calculator",
    "short_name": "BA Day",
    "description": "What today's Ignite starter kit sales put in the retailer's pocket.",
    "start_url": "./",
    "scope": "./",
    "display": "standalone",
    "orientation": "any",
    "background_color": "#eef0f6",
    "theme_color": "#1d2a5e",
    "icons": [
        {"src": "icons/icon-192.png", "sizes": "192x192", "type": "image/png", "purpose": "any maskable"},
        {"src": "icons/icon-512.png", "sizes": "512x512", "type": "image/png", "purpose": "any maskable"},
    ],
}
(ROOT / "manifest.webmanifest").write_text(json.dumps(manifest, indent=2) + "\n")

# Everything the app needs offline. The cache name changes whenever any file changes,
# so installed copies pick up updates the next time they open with signal.
assets = ["./", "index.html", "manifest.webmanifest"]
assets += sorted(str(p.relative_to(ROOT)) for d in ("fonts", "icons") for p in (ROOT / d).iterdir() if p.is_file())
h = hashlib.sha256()
for a in assets[1:]:
    h.update((ROOT / a).read_bytes())
version = h.hexdigest()[:10]

sw = f"""// Generated by build.py. Caches the whole app so it works offline.
const CACHE = "ba-day-{version}";
const ASSETS = {json.dumps(assets, indent=2)};

self.addEventListener("install", (e) => {{
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
}});

self.addEventListener("activate", (e) => {{
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
}});

// Cache first, so the app opens instantly with no signal; fall back to the network for anything new.
self.addEventListener("fetch", (e) => {{
  if (e.request.method !== "GET") return;
  e.respondWith(
    caches.match(e.request, {{ ignoreSearch: true }}).then((hit) =>
      hit || fetch(e.request).catch(() => e.request.mode === "navigate" ? caches.match("index.html") : Response.error())
    )
  );
}});
"""
(ROOT / "sw.js").write_text(sw)
print(f"Built index.html, manifest.webmanifest, sw.js (cache ba-day-{version}, {len(assets)} files)")
