// Generated by build.py. Caches the whole app so it works offline.
const CACHE = "ba-day-c0aa527d73";
const ASSETS = [
  "./",
  "index.html",
  "manifest.webmanifest",
  "fonts/Barlow-400.woff2",
  "fonts/Barlow-500.woff2",
  "fonts/Barlow-600.woff2",
  "fonts/Barlow-700.woff2",
  "fonts/BarlowCondensed-600.woff2",
  "fonts/BarlowCondensed-700.woff2",
  "fonts/BarlowCondensed-800.woff2",
  "fonts/fonts.css",
  "icons/apple-touch-icon.png",
  "icons/favicon-32.png",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/qr-app.svg"
];

self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

// Cache first, so the app opens instantly with no signal; fall back to the network for anything new.
self.addEventListener("fetch", (e) => {
  if (e.request.method !== "GET") return;
  e.respondWith(
    caches.match(e.request, { ignoreSearch: true }).then((hit) =>
      hit || fetch(e.request).catch(() => e.request.mode === "navigate" ? caches.match("index.html") : Response.error())
    )
  );
});
